FROM eclipse-temurin:21-jre-alpine

ARG APK_INSECURE_TLS=false

WORKDIR /app

RUN if [ "$APK_INSECURE_TLS" = "true" ]; then apk add --no-cache --no-check-certificate wget; else apk add --no-cache wget; fi

COPY app.jar /app/app.jar

EXPOSE 8080

ENV JAVA_OPTS=""

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
